### ISSUE TITLE
Clarify the flags for compiling local versus production

### ISSUE THREAD

**Issue by t-eckert** [microsoft/DevCookbook#10]
Currently, when you compile using the `compile.py` script, you must pass in a `--target` flag. However, this is confusing as `target` commonly refers to an output directory. In this case, it refers to the relative path set for links within the site so that a user can debug the site locally and still have it work correctly when published to GitHub pages.

While the behavior of what the switch does shouldn't change, the flag to switch it should. Instead of `-t`/`--target`, a user should pass no flag to compile for local and a `--prod` flag to compile for GitHub pages.

**Comment by demophoon** [comment]
Taking a look at this.
Hopefully commenting on this is enough to assign it to me.
